#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '
🏗️👷 Formatting code and checking formats
'

# Check Prettier standards
yarn format && yarn check-format ||
(
    echo '
    ❌ Prettier Check Failed. Add changes and try commit again.
    ';
    false;
)

echo '
✅ Formatting pass.
'

echo '
🏗️👷 Checking ESLint Standards
'

# Check ESLint Standards
yarn check-lint || (
    
    echo '
        🏗️👷 ESLint Check Failed. Trying to fix automagically.
        '
    yarn check-lint --fix && yarn check-lint

) ||
(
        echo '
        ❌ ESLint Check Failed.
        '
        false
)

echo '
✅ ESlint pass.
'

echo '
🏗️👷 Checking tsconfig standards
'

yarn check-types ||
(
    echo '
    Make the changes required above.
    '
    false;
)

echo '
✅ tsconfig standards check pass.
'

# If everything passes... Now we can commit
echo '🏗️👷 Generating build.'

yarn build ||
(
    echo '
    ❌ Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '
✅ Code commited with success!
'