#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Formatting code'


yarn format

echo '🏗️👷 Checking formats'

# Check Prettier standards
yarn check-format ||
(
    echo 'Prettier Check Failed. Run yarn format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
yarn check-lint ||
(
        echo 'ESLint Check Failed. Trying to fix it automagically.'
        eslint . --fix || echo 'Autofix failed' false;
         
)

# Check tsconfig standards
yarn check-types ||
(
    echo 'Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

yarn build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'