#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '
🏗️👷 Formatting code and checking formats.
'

# Check Prettier standards
yarn format ||
(
    echo '
    ❌ Prettier Check Failed. Add changes and try commit again.
    ';
    false;
)

echo '
✅ Formatting pass.
'

echo '
🏗️👷 Checking ESLint Standards.
'

# Check ESLint Standards
yarn check-lint --fix || (
    
    echo '
        ❌ ESLint Check Failed.
        '
    false

)

echo '
✅ ESlint pass.
'

echo '
🏗️👷 Checking NextJS ESLint Standards.
'

# Check ESLint Standards
yarn check-next-lint || (
    
    echo '
        ❌ NextJS ESLint Check Failed.
        '
    false

)

echo '
✅ NextJS ESlint pass.
'

echo '
🏗️👷 Checking tsconfig standards.
'

yarn check-types ||
(
    echo '
    Make the changes required above.
    '
    false;
)

echo '
✅ Tsconfig standards check pass.
'

# If everything passes... Now we can commit
git add .

echo '
✅ Code commited with success!
'